"""
Run Python (deepstats) pipeline on shared test data.

Loads data generated by generate_data.py and runs influence function inference.
"""

import numpy as np
import json
import sys
from pathlib import Path
from tqdm import tqdm

# Add project root
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from src.deepstats import get_dgp, get_family, influence, naive
from src.deepstats.models import StructuralNet, train_structural


class Config:
    """Minimal config for inference."""
    seed = 42
    epochs = 100
    lr = 0.01
    batch_size = 64
    weight_decay = 1e-4
    hidden_dims = [64, 32]
    n_folds = 50
    early_stopping = True
    patience = 10
    val_split = 0.1
    dropout = 0.1


def run_single_sim(sim_id: int, data_dir: Path) -> dict:
    """Run one simulation with deepstats."""

    # Load data
    X = np.loadtxt(data_dir / f'X_{sim_id}.csv', delimiter=',')
    T = np.loadtxt(data_dir / f'T_{sim_id}.csv', delimiter=',')
    Y = np.loadtxt(data_dir / f'Y_{sim_id}.csv', delimiter=',')
    beta_star = np.loadtxt(data_dir / f'beta_star_{sim_id}.csv', delimiter=',')
    mu_true = beta_star.mean()

    family = get_family('linear')
    config = Config()
    config.seed = 42 + sim_id

    # Run influence function inference
    result_if = influence(X, T, Y, family, config)

    # Run naive inference
    result_naive = naive(X, T, Y, family, config)

    # Check coverage
    ci_lower = result_if.mu_hat - 1.96 * result_if.se
    ci_upper = result_if.mu_hat + 1.96 * result_if.se
    if_covered = ci_lower <= mu_true <= ci_upper

    naive_se = result_naive.se
    naive_ci_lower = result_naive.mu_hat - 1.96 * naive_se
    naive_ci_upper = result_naive.mu_hat + 1.96 * naive_se
    naive_covered = naive_ci_lower <= mu_true <= naive_ci_upper

    return {
        'sim_id': sim_id,
        'mu_true': mu_true,
        'if_mu': result_if.mu_hat,
        'if_se': result_if.se,
        'if_covered': if_covered,
        'naive_mu': result_naive.mu_hat,
        'naive_se': naive_se,
        'naive_covered': naive_covered,
        'correction_ratio': result_if.correction_ratio,
    }


def main():
    data_dir = Path(__file__).parent / 'data'
    output_dir = Path(__file__).parent / 'results'
    output_dir.mkdir(exist_ok=True)

    # Load metadata
    with open(data_dir / 'metadata.json') as f:
        metadata = json.load(f)

    M = metadata['M']
    print("=" * 60)
    print("Running Python (deepstats) Pipeline")
    print("=" * 60)
    print(f"M = {M} simulations")
    print(f"N = {metadata['N']}, d = {metadata['d']}")
    print()

    results = []
    for sim_id in tqdm(range(M), desc="Python"):
        result = run_single_sim(sim_id, data_dir)
        results.append(result)

    # Aggregate results
    if_coverage = np.mean([r['if_covered'] for r in results])
    naive_coverage = np.mean([r['naive_covered'] for r in results])

    if_se_emp = np.std([r['if_mu'] for r in results])
    if_se_est = np.mean([r['if_se'] for r in results])
    if_ratio = if_se_est / if_se_emp if if_se_emp > 0 else float('nan')

    naive_se_emp = np.std([r['naive_mu'] for r in results])
    naive_se_est = np.mean([r['naive_se'] for r in results])
    naive_ratio = naive_se_est / naive_se_emp if naive_se_emp > 0 else float('nan')

    if_bias = np.mean([r['if_mu'] - r['mu_true'] for r in results])
    naive_bias = np.mean([r['naive_mu'] - r['mu_true'] for r in results])

    summary = {
        'implementation': 'python_deepstats',
        'M': M,
        'N': metadata['N'],
        'd': metadata['d'],
        'if_coverage': if_coverage,
        'if_se_empirical': if_se_emp,
        'if_se_estimated': if_se_est,
        'if_se_ratio': if_ratio,
        'if_bias': if_bias,
        'naive_coverage': naive_coverage,
        'naive_se_empirical': naive_se_emp,
        'naive_se_estimated': naive_se_est,
        'naive_se_ratio': naive_ratio,
        'naive_bias': naive_bias,
        'raw_results': results,
    }

    # Save results
    with open(output_dir / 'python_results.json', 'w') as f:
        json.dump(summary, f, indent=2)

    print()
    print("=" * 60)
    print("Python Results")
    print("=" * 60)
    print(f"{'':20} {'IF':>12} {'Naive':>12}")
    print("-" * 44)
    print(f"{'Coverage':20} {if_coverage:>11.1%} {naive_coverage:>11.1%}")
    print(f"{'SE (empirical)':20} {if_se_emp:>12.4f} {naive_se_emp:>12.4f}")
    print(f"{'SE (estimated)':20} {if_se_est:>12.4f} {naive_se_est:>12.4f}")
    print(f"{'SE Ratio':20} {if_ratio:>12.2f} {naive_ratio:>12.2f}")
    print(f"{'Bias':20} {if_bias:>12.4f} {naive_bias:>12.4f}")
    print()
    print(f"Results saved to: {output_dir / 'python_results.json'}")


if __name__ == '__main__':
    main()
